[package]
name = "rs-integration"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
kafka = "0.10.0"
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.40"
tracing-loki = "0.2.5"
tracing-subscriber = "0.3.18"
url = "2.5.2"
