[package]
name = "graphql"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "simple_graphql"
path = "bin/simple_graphql.rs"

[dependencies]
actix-cors = "0.7.1"
actix-web = "4.10.2"
env_logger = "0.11.8"
juniper = "0.16.1"
log = "0.4.27"
