name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install specific Rust version and set as default
    - name: Install Rust 1.85.1
      run: rustup install 1.85.1
    - name: Set default Rust version
      run: rustup default 1.85.1

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
