name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install specific Rust version and set as default
    - name: Install Rust 1.86.0
      run: rustup install 1.86.0
    - name: Set default Rust version
      run: rustup default 1.86.0
    - name: Install protobuf
      run: sudo apt update && sudo apt install -y protobuf-compiler

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
          
    - uses: actions/upload-artifact@v4
      with:
        name: build-target
        path: |
          target/debug/
          !target/debug/*.d
          !target/debug/*/*

